server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///xiaomi?serverTimezone=UTC
    username: root
    password: root

  mvc:
    view:
      static-path-pattern: /**
      #修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.cssl.pojo
  configuration-properties:
    auto-mapping-behavior: full
    use-generated-keys: true